name:                maquina-turing
version:             0.1.0.0
github:              "JPYamamoto/maquina-turing"
license:             MIT
author:              "Juan Pablo Yamamoto"
maintainer:          "jpyamamoto@ciencias.unam.mx"
copyright:           "2022 Juan Pablo Yamamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Una máquina universal de Turing. Acepta máquinas en JSON.
# category:            Academic

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JPYamamoto/maquina-turing#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.16
- aeson >= 1.5
- bytestring >= 0.10
- hashmap >= 1.3
- hashable >= 1.2

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  turing:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maquina-turing

tests:
  turing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maquina-turing
